[package]
name = "jaspy-nexus"
version = "0.1.0"
authors = ["Antti Tönkyrä <daedalus@pingtimeout.net>"]

[dependencies]
dotenv = "0.10.*"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
diesel = { version = "*", features = ["postgres"] }
diesel_codegen = { version = "*", features = ["postgres"] }
r2d2 = "*"
r2d2-diesel = "*"
time = "*"
zmq = "*"

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["json"]